# -*- coding: utf-8 -*-
"""data_loader

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7G33fAge5-IBVUHNr7ByGrMQ0c-3Cgt
"""

import pandas as pd
import sqlite3

conn = sqlite3.connect("ecommerce.db")

df_eligibility = pd.read_csv("eligibility_table.csv")
df_ads = pd.read_csv("ad_sales_metrics.csv")
df_sales = pd.read_csv("total_sales_metrics.csv")

df_eligibility.to_sql("eligibility_table", conn, if_exists="replace", index=False)
df_ads.to_sql("ad_sales_metrics", conn, if_exists="replace", index=False)
df_sales.to_sql("total_sales_metrics", conn, if_exists="replace", index=False)

print("✅ All tables loaded into ecommerce.db")