# -*- coding: utf-8 -*-
"""gemini_query

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l91zmJBMSFjWD9Se6rp_tCyTibCvDoCU
"""

import os
import google.generativeai as genai
from dotenv import load_dotenv

# Load .env variables
load_dotenv()
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

model = genai.GenerativeModel("gemini-pro")

def convert_question_to_sql(question: str) -> str:
    prompt = f"""
    You are a data analyst working with the following SQLite tables:

    Table: eligibility_table
    Columns: product_id (TEXT), is_eligible (BOOLEAN), eligibility_reason (TEXT)

    Table: ad_sales_metrics
    Columns: product_id (TEXT), impressions (INTEGER), clicks (INTEGER), cpc (REAL), ad_spend (REAL)

    Table: total_sales_metrics
    Columns: product_id (TEXT), units_sold (INTEGER), total_revenue (REAL)

    Convert the following question into a valid SQLite SQL query.
    Return ONLY the SQL statement.

    Question: {question}
    """
    response = model.generate_content(prompt)
    return response.text.strip()

# Commented out IPython magic to ensure Python compatibility.
# %pip install python-dotenv